[package]
name = "top-file-extensions"
version = "0.1.0"
authors = ["Frederik Braun <fbraun@mozilla.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.0.1"
